In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [2]:
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
                    'key2' : ['one', 'two', 'one', 'two', 'one'],
                    'data1' : np.random.randn(5),
                    'data2' : np.random.randn(5)})
df

  key1 key2     data1     data2
0    a  one  0.330709  0.890292
1    a  two  0.307811  0.848397
2    b  one  0.395301  0.461623
3    b  two -2.103299  0.874813
4    a  one -0.499327  1.490903

In [3]:
#key1으로 묶고 각 그룹에서 data1의 평균을 구하기
#groupby 호출 -> key1 컬럼을 넘김
grouped = df['data1'].groupby(df['key1'])
grouped # GroupBy 객체

In [4]:
grouped.mean()

key1
a    0.046398
b   -0.853999
Name: data1, dtype: float64

In [5]:
means = df['data1'].groupby([df['key1'], df['key2']]).mean()
means

key1  key2
a     one    -0.084309
      two     0.307811
b     one     0.395301
      two    -2.103299
Name: data1, dtype: float64

In [6]:
means.unstack()

key2       one       two
key1
a    -0.084309  0.307811
b     0.395301 -2.103299

In [7]:
states = np.array(['Ohio', 'California', 'California', 'Ohio', 'Ohio'])
years = np.array([2005, 2005, 2006, 2005, 2006])
df['data1'].groupby([states, years]).mean() #길이만 같다면 어떤 배열이라도 상관X

California  2005    0.307811
            2006    0.395301
Ohio        2005   -0.886295
            2006   -0.499327
Name: data1, dtype: float64

In [8]:
df.groupby('key1').mean() #'key2': 숫자가 아니기 때문에 계산결과에서 제외(nuisance column)

         data1     data2
key1
a     0.046398  1.076531
b    -0.853999  0.668218

In [9]:
df.groupby(['key1', 'key2']).mean()

              data1     data2
key1 key2
a    one  -0.084309  1.190598
     two   0.307811  0.848397
b    one   0.395301  0.461623
     two  -2.103299  0.874813

In [10]:
df.groupby(['key1', 'key2']).size() #그룹의 크기를 담고 있는 Series 반환

key1  key2
a     one     2
      two     1
b     one     1
      two     1
dtype: int64

In [11]:
#groupby : 이터레이션 지원 -> 그룹 이름, 데이터 묶음을 튜플로 반환
for name, group in df.groupby('key1'):
    print(name)
    print(group)

a
  key1 key2     data1     data2
0    a  one  0.330709  0.890292
1    a  two  0.307811  0.848397
4    a  one -0.499327  1.490903
b
  key1 key2     data1     data2
2    b  one  0.395301  0.461623
3    b  two -2.103299  0.874813

In [12]:
for (k1, k2), group in df.groupby(['key1', 'key2']): #인덱스 여러개 -> 튜플의 첫 번째 원소가 인덱스
    print((k1, k2))
    print(group)

('a', 'one')
  key1 key2     data1     data2
0    a  one  0.330709  0.890292
4    a  one -0.499327  1.490903
('a', 'two')
  key1 key2     data1     data2
1    a  two  0.307811  0.848397
('b', 'one')
  key1 key2     data1     data2
2    b  one  0.395301  0.461623
('b', 'two')
  key1 key2     data1     data2
3    b  two -2.103299  0.874813

In [13]:
pieces = dict(list(df.groupby('key1')))
pieces['b']

  key1 key2     data1     data2
2    b  one  0.395301  0.461623
3    b  two -2.103299  0.874813

In [14]:
df.dtypes

key1      object
key2      object
data1    float64
data2    float64
dtype: object

In [15]:
grouped = df.groupby(df.dtypes, axis = 1) #dtype에 따라 그룹으로 묶기

In [16]:
for dtype, group in grouped:
    print(dtype)
    print(group)

float64
      data1     data2
0  0.330709  0.890292
1  0.307811  0.848397
2  0.395301  0.461623
3 -2.103299  0.874813
4 -0.499327  1.490903
object
  key1 key2
0    a  one
1    a  two
2    b  one
3    b  two
4    a  one

In [17]:
df.groupby('key1')['data1'] #==df['data1'].groupby(df['key1'])
df.groupby('key1')[['data2']] #==df[['data2']].groupby(df['key1'])

In [18]:
df.groupby(['key1', 'key2'])[['data2']].mean()

              data2
key1 key2
a    one   1.190598
     two   0.848397
b    one   0.461623
     two   0.874813

In [19]:
s_grouped = df.groupby(['key1', 'key2'])['data2']
s_grouped.mean()

key1  key2
a     one     1.190598
      two     0.848397
b     one     0.461623
      two     0.874813
Name: data2, dtype: float64

In [20]:
people = pd.DataFrame(np.random.randn(5, 5),
                    columns=['a', 'b', 'c', 'd', 'e'],
                    index = ['Joe', 'Steve', 'Wes', 'Jim', 'Travis'])
people.iloc[2:3, [1, 2]] = np.nan 
people

               a         b         c         d         e
Joe     0.526525  0.331575 -0.162922  1.515917  0.142820
Steve   1.682493 -0.296963 -1.022969  1.258942  0.108636
Wes     0.621387       NaN       NaN -0.286832  0.434950
Jim    -1.046180 -1.311477 -0.180334  2.029273 -0.238786
Travis  1.062257 -0.049972 -0.365321  1.260641  1.094498

In [21]:
mapping = {'a' : 'red', 'b' : 'red', 'c' : 'blue', 'd' : 'blue', 'e' : 'red', 'f' : 'orange'}

In [22]:
by_column = people.groupby(mapping, axis = 1)
by_column.sum() # 'f' : 'orange' : 사용하지 않는 그룹 키도 문제 없음

            blue       red
Joe     1.352994  1.000920
Steve   0.235973  1.494166
Wes    -0.286832  1.056337
Jim     1.848938 -2.596443
Travis  0.895320  2.106783

In [23]:
map_series = pd.Series(mapping)
map_series

a       red
b       red
c      blue
d      blue
e       red
f    orange
dtype: object

In [24]:
people.groupby(map_series, axis = 1).count()

        blue  red
Joe        2    3
Steve      2    3
Wes        1    2
Jim        2    3
Travis     2    3

In [25]:
people.groupby(len).sum() #이름의 길이별로 그룹을 묶음 -> len : 이름의 길이가 담긴 배열을 만들어내는 함수

          a         b         c         d         e
3  0.101732 -0.979902 -0.343257  3.258357  0.338984
5  1.682493 -0.296963 -1.022969  1.258942  0.108636
6  1.062257 -0.049972 -0.365321  1.260641  1.094498

In [26]:
key_list = ['one', 'one', 'one', 'two', 'two']
people.groupby([len, key_list]).min() #함수를 배열, 사전 또는 Sereis와 섞어 쓰더라도 문제 X

              a         b         c         d         e
3 one  0.526525  0.331575 -0.162922 -0.286832  0.142820
  two -1.046180 -1.311477 -0.180334  2.029273 -0.238786
5 one  1.682493 -0.296963 -1.022969  1.258942  0.108636
6 two  1.062257 -0.049972 -0.365321  1.260641  1.094498

In [27]:
columns = pd.MultiIndex.from_arrays([['US', 'US', 'US', 'JP', 'JP'],
                                    [1, 3, 5, 1, 3]],
                                    names = ['cty', 'tenor'])

In [28]:
hier_df = pd.DataFrame(np.random.randn(4, 5), columns= columns)
hier_df

cty          US                            JP
tenor         1         3         5         1         3
0      1.512938  1.442569 -1.648982 -0.874506 -0.948795
1     -0.580514  1.348382  1.463500  0.952776  0.184529
2     -0.344209  1.149213 -0.538774  1.046906 -0.321624
3     -1.874870  0.318907 -1.620459 -0.668893 -0.461373

In [29]:
hier_df.groupby(level= 'cty', axis= 1).count()

cty  JP  US
0     2   3
1     2   3
2     2   3
3     2   3

In [30]:
df

  key1 key2     data1     data2
0    a  one  0.330709  0.890292
1    a  two  0.307811  0.848397
2    b  one  0.395301  0.461623
3    b  two -2.103299  0.874813
4    a  one -0.499327  1.490903

In [31]:
grouped = df.groupby('key1')

In [32]:
grouped['data1'].quantile(0.9) # quantile : 백분위수 구하기

key1
a    0.326129
b    0.145441
Name: data1, dtype: float64

In [33]:
def peak_to_peak(arr):
    return arr.max() - arr.min()

grouped.agg(peak_to_peak) #aggregate, agg : 원하는 함수에 데이터 집계할때

         data1     data2
key1
a     0.830035  0.642506
b     2.498600  0.413189

In [34]:
grouped.describe()

     data1                                                              \
     count      mean       std       min       25%       50%       75%
key1
a      3.0  0.046398  0.472750 -0.499327 -0.095758  0.307811  0.319260
b      2.0 -0.853999  1.766777 -2.103299 -1.478649 -0.853999 -0.229349

               data2                                                    \
           max count      mean       std       min       25%       50%
key1
a     0.330709   3.0  1.076531  0.359468  0.848397  0.869345  0.890292
b     0.395301   2.0  0.668218  0.292169  0.461623  0.564921  0.668218


           75%       max
key1
a     1.190598  1.490903
b     0.771515  0.874813

In [35]:
tips = pd.read_csv('C:/Users/seven/OneDrive/바탕 화면/Python Workspace/Python-master/Python for Data analysis/examples/tips.csv')
tips['tip_pct'] = tips['tip']/tips['total_bill']
tips[:6]

   total_bill   tip smoker  day    time  size   tip_pct
0       16.99  1.01     No  Sun  Dinner     2  0.059447
1       10.34  1.66     No  Sun  Dinner     3  0.160542
2       21.01  3.50     No  Sun  Dinner     3  0.166587
3       23.68  3.31     No  Sun  Dinner     2  0.139780
4       24.59  3.61     No  Sun  Dinner     4  0.146808
5       25.29  4.71     No  Sun  Dinner     4  0.186240

In [36]:
#컬럼에 따라 다른 함수 적용 or 여러 개의 함수를 한 번에 적용
grouped = tips.groupby(['day', 'smoker'])
grouped_pct = grouped['tip_pct']
grouped_pct.agg('mean')

day   smoker
Fri   No        0.151650
      Yes       0.174783
Sat   No        0.158048
      Yes       0.147906
Sun   No        0.160113
      Yes       0.187250
Thur  No        0.160298
      Yes       0.163863
Name: tip_pct, dtype: float64

In [37]:
grouped_pct.agg(['mean', 'std', peak_to_peak]) #함수 이름을 컬럼 이름으로 하는 DF 얻음

                 mean       std  peak_to_peak
day  smoker
Fri  No      0.151650  0.028123      0.067349
     Yes     0.174783  0.051293      0.159925
Sat  No      0.158048  0.039767      0.235193
     Yes     0.147906  0.061375      0.290095
Sun  No      0.160113  0.042347      0.193226
     Yes     0.187250  0.154134      0.644685
Thur No      0.160298  0.038774      0.193350
     Yes     0.163863  0.039389      0.151240

In [38]:
grouped_pct.agg([('foo', 'mean'), ('bar', np.std)]) # groupby 객체에서 컬럼 이름 바꾸기

                  foo       bar
day  smoker
Fri  No      0.151650  0.028123
     Yes     0.174783  0.051293
Sat  No      0.158048  0.039767
     Yes     0.147906  0.061375
Sun  No      0.160113  0.042347
     Yes     0.187250  0.154134
Thur No      0.160298  0.038774
     Yes     0.163863  0.039389

In [39]:
functions = ['count', 'mean', 'max']
result = grouped['tip_pct', 'total_bill'].agg(functions) # 여러 개의 함수를 여러 개의 컬럼에 적용
result

<ipython-input-39-461a72746424>:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  result = grouped['tip_pct', 'total_bill'].agg(functions) # 여러 개의 함수를 여러 개의 컬럼에 적용

            tip_pct                     total_bill
              count      mean       max      count       mean    max
day  smoker
Fri  No           4  0.151650  0.187735          4  18.420000  22.75
     Yes         15  0.174783  0.263480         15  16.813333  40.17
Sat  No          45  0.158048  0.291990         45  19.661778  48.33
     Yes         42  0.147906  0.325733         42  21.276667  50.81
Sun  No          57  0.160113  0.252672         57  20.506667  48.17
     Yes         19  0.187250  0.710345         19  24.120000  45.35
Thur No          45  0.160298  0.266312         45  17.113111  41.19
     Yes         17  0.163863  0.241255         17  19.190588  43.11

In [40]:
result['tip_pct']

             count      mean       max
day  smoker
Fri  No          4  0.151650  0.187735
     Yes        15  0.174783  0.263480
Sat  No         45  0.158048  0.291990
     Yes        42  0.147906  0.325733
Sun  No         57  0.160113  0.252672
     Yes        19  0.187250  0.710345
Thur No         45  0.160298  0.266312
     Yes        17  0.163863  0.241255

In [41]:
ftuples = [('Durchschnitt', 'mean'), ('Abweichung', np.var)]
grouped['tip_pct', 'total_bill'].agg(ftuples)

<ipython-input-41-417b40324039>:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  grouped['tip_pct', 'total_bill'].agg(ftuples)

                 tip_pct              total_bill
            Durchschnitt Abweichung Durchschnitt  Abweichung
day  smoker
Fri  No         0.151650   0.000791    18.420000   25.596333
     Yes        0.174783   0.002631    16.813333   82.562438
Sat  No         0.158048   0.001581    19.661778   79.908965
     Yes        0.147906   0.003767    21.276667  101.387535
Sun  No         0.160113   0.001793    20.506667   66.099980
     Yes        0.187250   0.023757    24.120000  109.046044
Thur No         0.160298   0.001503    17.113111   59.625081
     Yes        0.163863   0.001551    19.190588   69.808518

In [42]:
#컬럼마다 다른 함수 적용 -> agg에 컬럼 이름에 대응하는 함수가 들어있는 딕셔너리 전달
grouped.agg({'tip' : np.max, 'size' : 'sum'})

               tip  size
day  smoker
Fri  No       3.50     9
     Yes      4.73    31
Sat  No       9.00   115
     Yes     10.00   104
Sun  No       6.00   167
     Yes      6.50    49
Thur No       6.70   112
     Yes      5.00    40

In [43]:
grouped.agg({'tip_pct': ['min', 'max', 'mean', 'std'],
        'size' : 'sum'})

              tip_pct                               size
                  min       max      mean       std  sum
day  smoker
Fri  No      0.120385  0.187735  0.151650  0.028123    9
     Yes     0.103555  0.263480  0.174783  0.051293   31
Sat  No      0.056797  0.291990  0.158048  0.039767  115
     Yes     0.035638  0.325733  0.147906  0.061375  104
Sun  No      0.059447  0.252672  0.160113  0.042347  167
     Yes     0.065660  0.710345  0.187250  0.154134   49
Thur No      0.072961  0.266312  0.160298  0.038774  112
     Yes     0.090014  0.241255  0.163863  0.039389   40

In [44]:
tips.groupby(['day', 'smoker'], as_index= False).mean() #그룹키 조합 안만들기

    day smoker  total_bill       tip      size   tip_pct
0   Fri     No   18.420000  2.812500  2.250000  0.151650
1   Fri    Yes   16.813333  2.714000  2.066667  0.174783
2   Sat     No   19.661778  3.102889  2.555556  0.158048
3   Sat    Yes   21.276667  2.875476  2.476190  0.147906
4   Sun     No   20.506667  3.167895  2.929825  0.160113
5   Sun    Yes   24.120000  3.516842  2.578947  0.187250
6  Thur     No   17.113111  2.673778  2.488889  0.160298
7  Thur    Yes   19.190588  3.030000  2.352941  0.163863

In [45]:
def top(df, n = 5, column = 'tip_pct'):
    return df.sort_values(by = column)[-n:] #특정 컬럼에서 가장 큰 값을 가지는 로우를 선택하는 함수

top(tips, n = 6)

     total_bill   tip smoker  day    time  size   tip_pct
109       14.31  4.00    Yes  Sat  Dinner     2  0.279525
183       23.17  6.50    Yes  Sun  Dinner     4  0.280535
232       11.61  3.39     No  Sat  Dinner     2  0.291990
67         3.07  1.00    Yes  Sat  Dinner     1  0.325733
178        9.60  4.00    Yes  Sun  Dinner     2  0.416667
172        7.25  5.15    Yes  Sun  Dinner     2  0.710345

In [46]:
tips.groupby('smoker').apply(top)

            total_bill   tip smoker   day    time  size   tip_pct
smoker
No     88        24.71  5.85     No  Thur   Lunch     2  0.236746
       185       20.69  5.00     No   Sun  Dinner     5  0.241663
       51        10.29  2.60     No   Sun  Dinner     2  0.252672
       149        7.51  2.00     No  Thur   Lunch     2  0.266312
       232       11.61  3.39     No   Sat  Dinner     2  0.291990
Yes    109       14.31  4.00    Yes   Sat  Dinner     2  0.279525
       183       23.17  6.50    Yes   Sun  Dinner     4  0.280535
       67         3.07  1.00    Yes   Sat  Dinner     1  0.325733
       178        9.60  4.00    Yes   Sun  Dinner     2  0.416667
       172        7.25  5.15    Yes   Sun  Dinner     2  0.710345

In [47]:
tips.groupby(['smoker', 'day']).apply(top, n =1, column = 'total_bill') #추가적인 인자를 받을 때

                 total_bill    tip smoker   day    time  size   tip_pct
smoker day
No     Fri  94        22.75   3.25     No   Fri  Dinner     2  0.142857
       Sat  212       48.33   9.00     No   Sat  Dinner     4  0.186220
       Sun  156       48.17   5.00     No   Sun  Dinner     6  0.103799
       Thur 142       41.19   5.00     No  Thur   Lunch     5  0.121389
Yes    Fri  95        40.17   4.73    Yes   Fri  Dinner     4  0.117750
       Sat  170       50.81  10.00    Yes   Sat  Dinner     3  0.196812
       Sun  182       45.35   3.50    Yes   Sun  Dinner     3  0.077178
       Thur 197       43.11   5.00    Yes  Thur   Lunch     4  0.115982

In [48]:
tips.groupby(['smoker', 'day']).apply(top, n =2, column = 'total_bill')

                 total_bill    tip smoker   day    time  size   tip_pct
smoker day
No     Fri  91        22.49   3.50     No   Fri  Dinner     2  0.155625
            94        22.75   3.25     No   Fri  Dinner     2  0.142857
       Sat  59        48.27   6.73     No   Sat  Dinner     4  0.139424
            212       48.33   9.00     No   Sat  Dinner     4  0.186220
       Sun  112       38.07   4.00     No   Sun  Dinner     3  0.105070
            156       48.17   5.00     No   Sun  Dinner     6  0.103799
       Thur 85        34.83   5.17     No  Thur   Lunch     4  0.148435
            142       41.19   5.00     No  Thur   Lunch     5  0.121389
Yes    Fri  90        28.97   3.00    Yes   Fri  Dinner     2  0.103555
            95        40.17   4.73    Yes   Fri  Dinner     4  0.117750
       Sat  102       44.30   2.50    Yes   Sat  Dinner     3  0.056433
            170       50.81  10.00    Yes   Sat  Dinner     3  0.196812
       Sun  184       40.55   3.00    Yes   Sun  Dinner     2  0.073983
            182       45.35   3.50    Yes   Sun  Dinner     3  0.077178
       Thur 83        32.68   5.00    Yes  Thur   Lunch     2  0.152999
            197       43.11   5.00    Yes  Thur   Lunch     4  0.115982

In [49]:
tips.sort_values(by = 'total_bill')[-1:]

     total_bill   tip smoker  day    time  size   tip_pct
170       50.81  10.0    Yes  Sat  Dinner     3  0.196812

In [50]:
tips.sort_values(by = 'total_bill')[-2:]

     total_bill   tip smoker  day    time  size   tip_pct
212       48.33   9.0     No  Sat  Dinner     4  0.186220
170       50.81  10.0    Yes  Sat  Dinner     3  0.196812

In [51]:
tips.sort_values(by = 'total_bill')[-3:]

     total_bill    tip smoker  day    time  size   tip_pct
59        48.27   6.73     No  Sat  Dinner     4  0.139424
212       48.33   9.00     No  Sat  Dinner     4  0.186220
170       50.81  10.00    Yes  Sat  Dinner     3  0.196812

In [52]:
result = tips.groupby('smoker')['tip_pct'].describe()
result

,count,mean,std,min,25%,50%,75%,max
smoker,,,,,,,,
No,151.0,0.159328,0.039910,0.056797,0.136906,0.155625,0.185014,0.291990
Yes,93.0,0.163196,0.085119,0.035638,0.106771,0.153846,0.195059,0.710345

In [53]:
result.unstack('smoker')

       smoker
count  No        151.000000
       Yes        93.000000
mean   No          0.159328
       Yes         0.163196
std    No          0.039910
       Yes         0.085119
min    No          0.056797
       Yes         0.035638
25%    No          0.136906
       Yes         0.106771
50%    No          0.155625
       Yes         0.153846
75%    No          0.185014
       Yes         0.195059
max    No          0.291990
       Yes         0.710345
dtype: float64

In [54]:
#그룹 인덱스 생략하기
tips.groupby('smoker', group_keys= False).apply(top)

     total_bill   tip smoker   day    time  size   tip_pct
88        24.71  5.85     No  Thur   Lunch     2  0.236746
185       20.69  5.00     No   Sun  Dinner     5  0.241663
51        10.29  2.60     No   Sun  Dinner     2  0.252672
149        7.51  2.00     No  Thur   Lunch     2  0.266312
232       11.61  3.39     No   Sat  Dinner     2  0.291990
109       14.31  4.00    Yes   Sat  Dinner     2  0.279525
183       23.17  6.50    Yes   Sun  Dinner     4  0.280535
67         3.07  1.00    Yes   Sat  Dinner     1  0.325733
178        9.60  4.00    Yes   Sun  Dinner     2  0.416667
172        7.25  5.15    Yes   Sun  Dinner     2  0.710345

In [55]:
tips.groupby('smoker').apply(top)

            total_bill   tip smoker   day    time  size   tip_pct
smoker
No     88        24.71  5.85     No  Thur   Lunch     2  0.236746
       185       20.69  5.00     No   Sun  Dinner     5  0.241663
       51        10.29  2.60     No   Sun  Dinner     2  0.252672
       149        7.51  2.00     No  Thur   Lunch     2  0.266312
       232       11.61  3.39     No   Sat  Dinner     2  0.291990
Yes    109       14.31  4.00    Yes   Sat  Dinner     2  0.279525
       183       23.17  6.50    Yes   Sun  Dinner     4  0.280535
       67         3.07  1.00    Yes   Sat  Dinner     1  0.325733
       178        9.60  4.00    Yes   Sun  Dinner     2  0.416667
       172        7.25  5.15    Yes   Sun  Dinner     2  0.710345

In [56]:
frame = pd.DataFrame({'data1' : np.random.randn(1000),
                    'data2' : np.random.randn(1000)})

quartiles = pd.cut(frame.data1, 4) #pd.cut : 동일 길이로 나누어서 범주 만들기
quartiles # -3.3~-1.574 , -1.574~-0.145, 0.145 ~ 1.863 , 1.863 ~ 3.582

0       (0.0711, 1.637]
1       (0.0711, 1.637]
2      (-1.495, 0.0711]
3      (-3.067, -1.495]
4      (-1.495, 0.0711]
             ...
995    (-1.495, 0.0711]
996    (-1.495, 0.0711]
997    (-1.495, 0.0711]
998    (-1.495, 0.0711]
999     (0.0711, 1.637]
Name: data1, Length: 1000, dtype: category
Categories (4, interval[float64]): [(-3.067, -1.495] < (-1.495, 0.0711] < (0.0711, 1.637] < (1.637, 3.203]]

In [57]:
#cut에서 반환된 범주형객체는 바로 groupby로 넘길 수 있음 !
def get_stats(group):
    return {'min' : group.min(), 'max' : group.max(),
            'count' : group.count(), 'mean' : group.mean()}

grouped = frame.data2.groupby(quartiles)
grouped.apply(get_stats).unstack()

                       min       max  count      mean
data1
(-3.067, -1.495] -2.181629  2.564959   65.0 -0.053134
(-1.495, 0.0711] -3.045360  2.832729  467.0  0.030951
(0.0711, 1.637]  -2.666749  2.616240  425.0  0.000545
(1.637, 3.203]   -2.747186  1.589644   43.0 -0.266402

In [58]:
#그룹에 다른 값으로 결측치 채우기 -> fillna
#평균값으로 대체
s = pd.Series(np.random.randn(6))
s[::2] = np.nan
s

0         NaN
1    1.383015
2         NaN
3    0.249294
4         NaN
5    0.418115
dtype: float64

In [59]:
s.fillna(s.mean())

0    0.683474
1    1.383015
2    0.683474
3    0.249294
4    0.683474
5    0.418115
dtype: float64

In [60]:
#그룹별로 채우고 싶은 값이 다를때 -> 그룹으로 나누고 apply & 각 그룹에 대해 fillna
states = ['Ohio', 'New York', 'Vermont', 'Florida', 'Oregon', 'Nevada', 'California', 'Idaho']
group_key = ['East']*4 + ['West']*4
data  = pd.Series(np.random.randn(8), index = states)
data

Ohio         -1.029652
New York     -0.458439
Vermont      -2.786199
Florida       0.767942
Oregon        0.264026
Nevada       -1.000820
California   -0.305899
Idaho         0.146805
dtype: float64

In [61]:
data[['Vermont', 'Nevada', 'Idaho']] = np.nan
data

Ohio         -1.029652
New York     -0.458439
Vermont            NaN
Florida       0.767942
Oregon        0.264026
Nevada             NaN
California   -0.305899
Idaho              NaN
dtype: float64

In [62]:
data.groupby(group_key).mean()

East   -0.240050
West   -0.020936
dtype: float64

In [63]:
fill_mean = lambda g : g.fillna(g.mean())

data.groupby(group_key).apply(fill_mean)

Ohio         -1.029652
New York     -0.458439
Vermont      -0.240050
Florida       0.767942
Oregon        0.264026
Nevada       -0.020936
California   -0.305899
Idaho        -0.020936
dtype: float64

In [64]:
#그룹에 따라 미리 정의된 다른 값 채워넣기
fill_values = {'East' : 0.5, 'West' : -1}
fill_func = lambda g: g.fillna(fill_values[g.name])
data.groupby(group_key).apply(fill_func)

Ohio         -1.029652
New York     -0.458439
Vermont       0.500000
Florida       0.767942
Oregon        0.264026
Nevada       -1.000000
California   -0.305899
Idaho        -1.000000
dtype: float64

In [65]:
suits = ['H', 'S', 'C', 'D'] #하트, 스페이드, 클럽, 다이아몬드
card_val = (list(range(1,11)) + [10]*3)*4
base_names = ['A'] + list(range(2,11)) + ['J', 'K', 'Q']
cards = []
for suit in ['H', 'S', 'C', 'D'] :
    cards.extend(str(num) + suit for num in base_names)

deck = pd.Series(card_val, index= cards)
deck

AH      1
2H      2
3H      3
4H      4
5H      5
6H      6
7H      7
8H      8
9H      9
10H    10
JH     10
KH     10
QH     10
AS      1
2S      2
3S      3
4S      4
5S      5
6S      6
7S      7
8S      8
9S      9
10S    10
JS     10
KS     10
QS     10
AC      1
2C      2
3C      3
4C      4
5C      5
6C      6
7C      7
8C      8
9C      9
10C    10
JC     10
KC     10
QC     10
AD      1
2D      2
3D      3
4D      4
5D      5
6D      6
7D      7
8D      8
9D      9
10D    10
JD     10
KD     10
QD     10
dtype: int64

In [66]:
def draw(deck, n = 5) : 
    return deck.sample(n)

draw(deck)

QD    10
9D     9
6H     6
6C     6
2D     2
dtype: int64

In [67]:
get_suit = lambda card : card[-1] # 마지막 글자가 세트
deck.groupby(get_suit).apply(draw, n = 2)
# 각 세트별로 2장의 카드 무작위 추출

C  KC     10
   4C      4
D  KD     10
   8D      8
H  10H    10
   QH     10
S  QS     10
   2S      2
dtype: int64

In [68]:
deck.groupby(get_suit, group_keys = False).apply(draw, n = 2)

AC     1
5C     5
2D     2
8D     8
3H     3
8H     8
KS    10
9S     9
dtype: int64

In [69]:
#그룹 가중 평균과 상관관계
df = pd.DataFrame({'category' : ['a', 'a', 'a', 'a', 'b', 'b', 'b', 'b'],
                    'data' : np.random.randn(8),
                    'weights' : np.random.randn(8)})
df

  category      data   weights
0        a -0.603875  1.881262
1        a -0.065992 -0.980620
2        a -0.585141  0.561740
3        a -1.909126  0.122676
4        b -0.560730 -0.314287
5        b  0.026196  1.103358
6        b -1.556414 -1.902983
7        b -0.127770 -0.990690

In [70]:
grouped  = df.groupby('category')
get_wavg = lambda g: np.average(g['data'], weights=g['weights'])
grouped.apply(get_wavg) #그룹별 가중 평균

category
a   -1.031025
b   -1.564924
dtype: float64

In [71]:
close_px = pd.read_csv('C:/Users/seven/OneDrive/바탕 화면/Python Workspace/Python-master/Python for Data analysis/examples/stock_px_2.csv', parse_dates = True, index_col = 0) 
# parse_dates : 파일에 날짜/시간이 있을때 형태에 알맞게 가져오기
# index_col : row에 있는 값 column의 인덱스로
close_px.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2214 entries, 2003-01-02 to 2011-10-14
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AAPL    2214 non-null   float64
 1   MSFT    2214 non-null   float64
 2   XOM     2214 non-null   float64
 3   SPX     2214 non-null   float64
dtypes: float64(4)
memory usage: 86.5 KB

In [72]:
close_px[-4:]

              AAPL   MSFT    XOM      SPX
2011-10-11  400.29  27.00  76.27  1195.54
2011-10-12  402.19  26.96  77.16  1207.25
2011-10-13  408.43  27.18  76.37  1203.66
2011-10-14  422.00  27.27  78.11  1224.58

In [73]:
spx_corr = lambda x: x.corrwith(x['SPX']) #'SPX'컬럼과 다른 컬럼의 상관관계를 계산

In [74]:
rets = close_px.pct_change().dropna() # close_px의 퍼센트 변화율 계산 
get_year = lambda x: x.year # 각 datetime에서 연도 속성만 반환하는 함수

by_year = rets.groupby(get_year)
by_year.apply(spx_corr) # 연도벼 퍼센트 변화율

          AAPL      MSFT       XOM  SPX
2003  0.541124  0.745174  0.661265  1.0
2004  0.374283  0.588531  0.557742  1.0
2005  0.467540  0.562374  0.631010  1.0
2006  0.428267  0.406126  0.518514  1.0
2007  0.508118  0.658770  0.786264  1.0
2008  0.681434  0.804626  0.828303  1.0
2009  0.707103  0.654902  0.797921  1.0
2010  0.710105  0.730118  0.839057  1.0
2011  0.691931  0.800996  0.859975  1.0

In [75]:
#두 컬럼 간의 상관관계 계산
by_year.apply(lambda g: g['AAPL'].corr(g['MSFT']))

2003    0.480868
2004    0.259024
2005    0.300093
2006    0.161735
2007    0.417738
2008    0.611901
2009    0.432738
2010    0.571946
2011    0.581987
dtype: float64

In [78]:
import statsmodels.api as sm
def regress(data, yvar, xvars):
    Y = data[yvar]
    X = data[xvars]
    X['intercept'] = 1.
    result = sm.OLS(Y, X).fit()
    return result.params

In [79]:
by_year.apply(regress, 'AAPL', ['SPX'])

           SPX  intercept
2003  1.195406   0.000710
2004  1.363463   0.004201
2005  1.766415   0.003246
2006  1.645496   0.000080
2007  1.198761   0.003438
2008  0.968016  -0.001110
2009  0.879103   0.002954
2010  1.052608   0.001261
2011  0.806605   0.001514

In [80]:
#피벗테이블 : 데이터 요약화 도구 -> 데이터를 키로 수집해서 어떤 키는 로우에, 어떤 키는 컬럼에 나열해서 데이터를 정렬
#pivot_table -> pandas 모듈의 최상위 함수
#마진 : 부분합을 추가할 수 있는 기능을 제공
tips.pivot_table(index = ['day', 'smoker']) #요일과 흡연자 집단에서 평균 (pivot_table의 기본 연산)

                 size       tip   tip_pct  total_bill
day  smoker
Fri  No      2.250000  2.812500  0.151650   18.420000
     Yes     2.066667  2.714000  0.174783   16.813333
Sat  No      2.555556  3.102889  0.158048   19.661778
     Yes     2.476190  2.875476  0.147906   21.276667
Sun  No      2.929825  3.167895  0.160113   20.506667
     Yes     2.578947  3.516842  0.187250   24.120000
Thur No      2.488889  2.673778  0.160298   17.113111
     Yes     2.352941  3.030000  0.163863   19.190588

In [82]:
tips.pivot_table(['tip_pct', 'size'], index= ['time', 'day'], columns= 'smoker') 
#tip_pct와 size에 대해서만 집계, 날짜별로 그룹화, 이를 위해 day 로우와 smoker 컬럼 추가

                 size             tip_pct
smoker             No       Yes        No       Yes
time   day
Dinner Fri   2.000000  2.222222  0.139622  0.165347
       Sat   2.555556  2.476190  0.158048  0.147906
       Sun   2.929825  2.578947  0.160113  0.187250
       Thur  2.000000       NaN  0.159744       NaN
Lunch  Fri   3.000000  1.833333  0.187735  0.188937
       Thur  2.500000  2.352941  0.160311  0.163863

In [83]:
tips.pivot_table(['tip_pct', 'size'], index= ['time', 'day'], columns= 'smoker', margins= True) 
#부분합 포함 -> all 컬럼과 all 로우가 추가

                 size                       tip_pct
smoker             No       Yes       All        No       Yes       All
time   day
Dinner Fri   2.000000  2.222222  2.166667  0.139622  0.165347  0.158916
       Sat   2.555556  2.476190  2.517241  0.158048  0.147906  0.153152
       Sun   2.929825  2.578947  2.842105  0.160113  0.187250  0.166897
       Thur  2.000000       NaN  2.000000  0.159744       NaN  0.159744
Lunch  Fri   3.000000  1.833333  2.000000  0.187735  0.188937  0.188765
       Thur  2.500000  2.352941  2.459016  0.160311  0.163863  0.161301
All          2.668874  2.408602  2.569672  0.159328  0.163196  0.160803

In [84]:
tips.pivot_table('tip_pct', index = ['time', 'smoker'], columns= 'day', aggfunc= len, margins= True)

day             Fri   Sat   Sun  Thur    All
time   smoker
Dinner No       3.0  45.0  57.0   1.0  106.0
       Yes      9.0  42.0  19.0   NaN   70.0
Lunch  No       1.0   NaN   NaN  44.0   45.0
       Yes      6.0   NaN   NaN  17.0   23.0
All            19.0  87.0  76.0  62.0  244.0

In [85]:
tips.pivot_table('tip_pct', index = ['time', 'size', 'smoker'], columns= 'day', aggfunc='mean', fill_value = 0) #fill_value : 어떤 조합이 비어있을때

day                      Fri       Sat       Sun      Thur
time   size smoker
Dinner 1    No      0.000000  0.137931  0.000000  0.000000
            Yes     0.000000  0.325733  0.000000  0.000000
       2    No      0.139622  0.162705  0.168859  0.159744
            Yes     0.171297  0.148668  0.207893  0.000000
       3    No      0.000000  0.154661  0.152663  0.000000
            Yes     0.000000  0.144995  0.152660  0.000000
       4    No      0.000000  0.150096  0.148143  0.000000
            Yes     0.117750  0.124515  0.193370  0.000000
       5    No      0.000000  0.000000  0.206928  0.000000
            Yes     0.000000  0.106572  0.065660  0.000000
       6    No      0.000000  0.000000  0.103799  0.000000
Lunch  1    No      0.000000  0.000000  0.000000  0.181728
            Yes     0.223776  0.000000  0.000000  0.000000
       2    No      0.000000  0.000000  0.000000  0.166005
            Yes     0.181969  0.000000  0.000000  0.158843
       3    No      0.187735  0.000000  0.000000  0.084246
            Yes     0.000000  0.000000  0.000000  0.204952
       4    No      0.000000  0.000000  0.000000  0.138919
            Yes     0.000000  0.000000  0.000000  0.155410
       5    No      0.000000  0.000000  0.000000  0.121389
       6    No      0.000000  0.000000  0.000000  0.173706

In [86]:
tips.pivot_table('tip_pct', index = ['time', 'size', 'smoker'], columns= 'day', aggfunc='mean')

day                      Fri       Sat       Sun      Thur
time   size smoker
Dinner 1    No           NaN  0.137931       NaN       NaN
            Yes          NaN  0.325733       NaN       NaN
       2    No      0.139622  0.162705  0.168859  0.159744
            Yes     0.171297  0.148668  0.207893       NaN
       3    No           NaN  0.154661  0.152663       NaN
            Yes          NaN  0.144995  0.152660       NaN
       4    No           NaN  0.150096  0.148143       NaN
            Yes     0.117750  0.124515  0.193370       NaN
       5    No           NaN       NaN  0.206928       NaN
            Yes          NaN  0.106572  0.065660       NaN
       6    No           NaN       NaN  0.103799       NaN
Lunch  1    No           NaN       NaN       NaN  0.181728
            Yes     0.223776       NaN       NaN       NaN
       2    No           NaN       NaN       NaN  0.166005
            Yes     0.181969       NaN       NaN  0.158843
       3    No      0.187735       NaN       NaN  0.084246
            Yes          NaN       NaN       NaN  0.204952
       4    No           NaN       NaN       NaN  0.138919
            Yes          NaN       NaN       NaN  0.155410
       5    No           NaN       NaN       NaN  0.121389
       6    No           NaN       NaN       NaN  0.173706