 # 자료형
표현식 = value로 가장 많은 타입은 정수이다. (숫자형 4가지로 구성)  

identity expression으로 표현 가능한 것.  
오른쪽 하나의 결과값으로 표현할 수 있다. (함수 , 리스트 등등)

In [219]:
a=1

## 정수형의 특징
arbitary precision
- 숫자의 범위가 없다. 무한대까지 정수의 형태를 만들 수 있다.

In [220]:
1==1 # 값을 비교

True

In [221]:
1 is 1 # memory를 비교

<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-221-9ef9bbd4944b>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  1 is 1 # memory를 비교

True

In [222]:
a = 1000
b = 1000
a is b # False

False

In [223]:
0b03 #literal

SyntaxError: invalid digit '3' in binary literal (<ipython-input-223-07b3a56f72c7>, line 1)

## literal
literal : 데이터를 생성하기 위해서 쓰는 특수기호
ex) 대괄호 등

In [230]:
a = 255
b = 255
a is b # True    #속도가 느리기 때문에 새로 생성하는 것이 아니라 캐시를 해버림.

True

In [231]:
import antigravity

## 부동소수점
컴퓨터는 정확하게 계산할 수 없다.
floating point
float은 숫자의 범위가 있음

In [232]:
# 부동소수점
0.1+0.1+0.1

0.30000000000000004

In [233]:
round(1.5)

2

In [234]:
round(2.5)

2

In [235]:
import sys

In [236]:
sys.float_info

sys.float_info(max=1.7976931348623157e+308, max_exp=1024, max_10_exp=308, min=2.2250738585072014e-308, min_exp=-1021, min_10_exp=-307, dig=15, mant_dig=53, epsilon=2.220446049250313e-16, radix=2, rounds=1)

In [237]:
1.7976931348623157e+308+1 == 1.7976931348623157e+308

True

In [238]:
1.7976931348623157e+309

inf

숫자의 패턴을 알고 있어야 한다.

파이썬 coercion : 정수와 소수를 더하면 항상 소수가 된다는 보장이 없다. (암시적 형변환)
complex : 복소수

In [239]:
import pandas as pd

## bool type
True는 1 False는 0

In [240]:
type(True)

bool

In [241]:
True

True

In [242]:
issubclass(bool,int)

True

# 정수형

In [243]:
#유니코드
'문근영'

'문근영'

In [244]:
#byte코드
b'문근영'

SyntaxError: bytes can only contain ASCII literal characters. (<ipython-input-244-58ae68848700>, line 2)

In [245]:
b'moon'

b'moon'

In [246]:
memoryview

memoryview

In [247]:
100

100

In [248]:
n

NameError: name 'n' is not defined

### container  

numpy -> homo 구조로 만들었다.  
문자는 homo  

sequencial vs not sequencial이냐  
sequencial : set, dictionary  
not sequencial

In [249]:
import numpy as np

In [250]:
a= np.array([1,2,3,'4'])
a

array(['1', '2', '3', '4'], dtype='<U11')

In [251]:
import tensorflow as tf

In [252]:
a=tf.constant([1,2,3,4]) #homo로만 구성해야한다.

## duck-typing

__len__ , __getitem__        둘 다 있으면 덕타이핑 (인덱싱과 슬라이싱이 가능하다.)

In [253]:
a[0]

In [254]:
a[:]

In [255]:
b={1,2}

In [256]:
dir(b)

['__and__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__iand__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__isub__',
 '__iter__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__ror__',
 '__rsub__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__xor__',
 'add',
 'clear',
 'copy',
 'difference',
 'difference_update',
 'discard',
 'intersection',
 'intersection_update',
 'isdisjoint',
 'issubset',
 'issuperset',
 'pop',
 'remove',
 'symmetric_difference',
 'symmetric_difference_update',
 'union',
 'update']

mutable vs inmutable
bytes array : mutable

In [257]:
range(10)[4]

4

In [258]:
a=1,2

In [259]:
a  #tuple

(1, 2)

In [260]:
def x():
    return 1,2
x()

(1, 2)

In [261]:
for i in 1,2,3,4:
    print(i)

1
2
3
4

In [262]:
pd.DataFrame.from_record

AttributeError: type object 'DataFrame' has no attribute 'from_record'

In [263]:
import seaborn as sns
iris = sns.load_dataset('iris')

def t(*a):
    return a
t(1,2,3,4,5)

(1, 2, 3, 4, 5)

### tuple은 형태가 일정한 inmutable이다.

In [264]:
a = 1
id(a)

140723084142384

In [265]:
type(a)

int

재할당 : 다시 할당한느 것  
상수 : 할당할 수 없는 수  
파이썬은 상수가 없다. (재할당 무조건 가능)  
keyword 뺴고 가능

In [266]:
a = 2

import keyword

In [267]:
import keyword

In [268]:
keyword.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [269]:
a=[1,2,3]

In [270]:
id(a)

2894816456064

In [271]:
a.append(4)
a

[1, 2, 3, 4]

In [272]:
id(a)

2894816456064

In [273]:
import tensorflow as tf

In [274]:
x= tf.keras.applications.VGG16()

Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/vgg16/vgg16_weights_tf_dim_ordering_tf_kernels.h5
172711936/553467096 [========>.....................] - ETA: 33s

KeyboardInterrupt:

In [275]:
x.weights

AttributeError: 'function' object has no attribute 'weights'

In [276]:
a=[1,2,3]
def X(a):
    return a.append(4)
X(a)

## mutable 3
append  
pop  
index

In [277]:
b=a.append(4)

In [278]:
b is None

True

In [279]:
c=a.pop()
c

4

In [280]:
a.index(3)

2

In [281]:
import seaborn as sns
iris = sns.load_dataset('iris')
iris .drop(columns='sepal_length')

     sepal_width  petal_length  petal_width    species
0            3.5           1.4          0.2     setosa
1            3.0           1.4          0.2     setosa
2            3.2           1.3          0.2     setosa
3            3.1           1.5          0.2     setosa
4            3.6           1.4          0.2     setosa
..           ...           ...          ...        ...
145          3.0           5.2          2.3  virginica
146          2.5           5.0          1.9  virginica
147          3.0           5.2          2.0  virginica
148          3.4           5.4          2.3  virginica
149          3.0           5.1          1.8  virginica

[150 rows x 4 columns]

In [282]:
frozenset

frozenset

In [283]:
def t(t):
    a=t*t
    return a
def s(t):
    return t*t

In [284]:
import dis

In [285]:
dis.dis(t)

  2           0 LOAD_FAST                0 (t)
              2 LOAD_FAST                0 (t)
              4 BINARY_MULTIPLY
              6 STORE_FAST               1 (a)

  3           8 LOAD_FAST                1 (a)
             10 RETURN_VALUE

In [286]:
dis.dis(s)

  5           0 LOAD_FAST                0 (t)
              2 LOAD_FAST                0 (t)
              4 BINARY_MULTIPLY
              6 RETURN_VALUE

#### set

In [287]:
a={3,2,1}

In [288]:
a

{1, 2, 3}

In [289]:
b={2,3,4}

In [290]:
b

{2, 3, 4}

In [291]:
a-b #차

{1}

In [292]:
a&b #교집합

{2, 3}

In [293]:
a|b #합집합

{1, 2, 3, 4}

In [294]:
c = tf.Variable([1,2,3])

In [295]:
c.assign([2,3,4])

In [296]:
c

In [297]:
d=frozenset([1,2,3])

In [298]:
{}

{}

In [299]:
set()

set()

In [300]:
y=[1,2,3]

In [301]:
x={'a':1}

In [302]:
x['b']=4

In [303]:
x

{'a': 1, 'b': 4}

In [304]:
x={1:1}

In [305]:
zz={(1,2,3) :1} #tuple 안 list는 안됨.

In [306]:
z=dict(a=1)

In [307]:
z

{'a': 1}

In [308]:
#dictunary 많이 사용하라
# 데이터를 뽑기 쉬움. list처럼 key를 숫자로 집어넣어서 사용할 수도 있다.
# expression은 하나의 결과값으로 축약할 수 있다.
#오른쪽에 올 수 있다.

In [309]:
a=1

In [310]:
from sklearn.datasets import load_boston

In [311]:
import tensorflow as tf

In [312]:
tf.keras.losses.binary_crossentropy
tf.keras.losses.BinaryCrossentropy
-camel binaryCrossentropy
-CapsWord (pascal) BinaryCrossentropy

python <= camel == pascal

SyntaxError: invalid syntax (<ipython-input-312-55e1b553871f>, line 3)

In [313]:
a=1,2,3, # , : trailing comma

In [314]:
a, b = 1,2

In [315]:
a, b = b, a

In [316]:
a, b=0,1
def fib2(n):
    result=[]
    while a<n:
        result.append()
        a,b=b,a+b
    return resuilt

In [317]:
a,*b =1,2,3 #unpacking
#*b : 리스트
b

[2, 3]

In [318]:
a,*b,c=(1,2,3,4,5)

In [319]:
b

[2, 3, 4]

In [320]:
*a,=(1,2,3,4,5)

In [321]:
a #tuple을 list로 변환시킬 수 있음

[1, 2, 3, 4, 5]

In [322]:
a=b=[1,2,3]

In [323]:
c=b.copy()

In [324]:
c.append(4)

In [325]:
a

[1, 2, 3]

In [326]:
# 데이터 분석에서 copy / checkpoint 하는 것이 중요!
# 분석 진행에 있어 뒤로 못 돌린다.

In [327]:
b == b[:]

True

In [328]:
b is b[:] #메모리 번지가 다르다.

False

In [329]:
c=b
c.append(4)
a

[1, 2, 3, 4]

In [330]:
import seaborn as sns
iris[['petal_width','species']]

     petal_width    species
0            0.2     setosa
1            0.2     setosa
2            0.2     setosa
3            0.2     setosa
4            0.2     setosa
..           ...        ...
145          2.3  virginica
146          1.9  virginica
147          2.0  virginica
148          2.3  virginica
149          1.8  virginica

[150 rows x 2 columns]

In [331]:
a=b=[[1,2],[3,4]]

In [332]:
c=a

In [333]:
c[0][0]=100

In [334]:
a

[[100, 2], [3, 4]]

In [335]:
b

[[100, 2], [3, 4]]

In [336]:
import copy

In [337]:
c=copy.deepcopy(a)

In [338]:
c[0][0]=100

In [339]:
c

[[100, 2], [3, 4]]

In [340]:
a

[[100, 2], [3, 4]]

In [341]:
import tensorflow as tf

In [342]:
len(tf.keras.datasets.mnist.load_data())

2

In [343]:
a,b = tf.keras.datasets.mnist.load_data()

In [344]:
len(a)

2

In [345]:
x,y=a ; u,w=b

In [346]:
(x,y),(u,w) = tf.keras.datasets.mnist.load_data()

In [347]:
if 3:
    print('a')
else:
    print('b')

a

In [348]:
if 0: #0. , "", [], None, list(), float(), tuple() 등등 : 없는 것은 다 거짓(False)라고 나타낸다.
    print('a')
else:
    print('b')
    #0 제외하고 다 a임.

b

In [349]:
False == None #False : 0이고, None는 0이 아니다.

False

In [350]:
import this
#Although that way may not be obvious at first unless you're Dutch

In [351]:
3 and 4 #short serkit (and : 앞만 반환)
# 앞 -> 참이면 뒷
# 앞 -> 거짓이면 앞

4

In [353]:
[] and 4
# []는 비어있으니까 거짓 -> 앞을 출력

[]

In [352]:
4 or 5
#앞 -> 참이면 앞
#앞 -> 거짓이면 뒤

4

In [356]:
help('in')

Membership test operations
**************************

The operators "in" and "not in" test for membership.  "x in s"
evaluates to "True" if *x* is a member of *s*, and "False" otherwise.
"x not in s" returns the negation of "x in s".  All built-in sequences
and set types support this as well as dictionary, for which "in" tests
whether the dictionary has a given key. For container types such as
list, tuple, set, frozenset, dict, or collections.deque, the
expression "x in y" is equivalent to "any(x is e or x == e for e in
y)".

For the string and bytes types, "x in y" is "True" if and only if *x*
is a substring of *y*.  An equivalent test is "y.find(x) != -1".
Empty strings are always considered to be a substring of any other
string, so """ in "abc"" will return "True".

For user-defined classes which define the "__contains__()" method, "x
in y" returns "True" if "y.__contains__(x)" returns a true value, and
"False" otherwise.

For user-defined classes which do not define "__contains__()" but do
define "__iter__()", "x in y" is "True" if some value "z", for which
the expression "x is z or x == z" is true, is produced while iterating
over "y". If an exception is raised during the iteration, it is as if
"in" raised that exception.

Lastly, the old-style iteration protocol is tried: if a class defines
"__getitem__()", "x in y" is "True" if and only if there is a non-
negative integer index *i* such that "x is y[i] or x == y[i]", and no
lower integer index raises the "IndexError" exception.  (If any other
exception is raised, it is as if "in" raised that exception).

The operator "not in" is defined to have the inverse truth value of
"in".

Related help topics: SEQUENCEMETHODS

In [357]:
1 in [1,2,3]

True

In [358]:
'1' in [1,2,3] #hetero type

False

In [359]:
'1' in '12345'

True

In [361]:
1 in '12345' #error homo에 1을 대입하면 error 가 뜬다.

TypeError: 'in <string>' requires string as left operand, not int

In [362]:
'1' not in '1234'

False

In [365]:
'1' in {1:'1'} #딕셔너리의 경우 key만 check

False

In [368]:
for i in {1:2,3:4,5:6}:
    print(i) #딕셔너리니까 key만 check
    #in 다음에 올 수 있는 것 : iterable

1
3
5

__getitem__ , __len__ :sequence type  
__iter__ : iterable

In [369]:
a=[1,2,3]

In [370]:
'__iter__' in dir(a)

True

In [371]:
class A:
    pass

In [372]:
a = A()

In [373]:
for i in a:
    print(i) #iterable 하지 않는다.. -> iterable 알아야 한다.

TypeError: 'A' object is not iterable

In [378]:
class B:
    def __iter__(self):
        return iter('12')

In [379]:
b=B()

In [380]:
for i in b:
    print(i)

1
2

In [381]:
import itertoolsa

ModuleNotFoundError: No module named 'itertoolsa'

In [382]:
from collections import Iterable,Iterator

<ipython-input-382-0a4523aabcc8>:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import Iterable,Iterator

In [383]:
from sklearn.naive_bayes import ABCMeta

In [384]:
import dis

In [386]:
dis.dis(X)

  3           0 LOAD_FAST                0 (a)
              2 LOAD_METHOD              0 (append)
              4 LOAD_CONST               1 (4)
              6 CALL_METHOD              1
              8 RETURN_VALUE

In [387]:
for i in [1,2,3]:
    print(i)
else:
    print('end')

1
2
3
end

In [388]:
for i in range(10):
    if i==5:
        continue
    print(i)
else:
    print('end')

0
1
2
3
4
6
7
8
9
end

In [391]:
i =10
while (i>10):
    i -=1
    print(i)
else:
    print('end') #break가 걸리지 않고 0번 반복했다는 뜻.
    
    # else가 if에만 쓰이는 것이 아니라 for, while에도 쓰이는 것임.
    # 그렇지만 else 쓰이지 않는 이유 : 의사소통이 안된다 ㅋㅋ

end

In [392]:
## 용어 정리

In [393]:
# 파라미터 (parameter)
# 인자 (argument)

In [395]:
def x(a):
    return a

In [397]:
x(3) # 3: 인자

3

In [402]:
def x(a):
    return a

In [403]:
#x  
#x()
#x(a) 
#여기서 함수 : x 이다.
#괄호를 붙일 수 있는 것이 따로 존재.

In [405]:
callable(x)

True

In [406]:
class A:
    pass

In [407]:
callable(A)

True

In [408]:
A()

In [410]:
def x(a,b=1):
    return a+b

In [412]:
x(1)

2

In [414]:
x(1,2)

3

In [415]:
# 키워드 방식
x(b=1,a=2)

3

In [416]:
#positional 방식
x(2,3)

5

In [417]:
len([1,2,3])

3

In [418]:
len(obj=[1,2,3]) # / 기준으로 왼쪽은 positional 방식으로만 사용 가능하다.

TypeError: len() takes no keyword arguments

In [420]:
import matplotlib.pyplot as plt

In [421]:
plt.plot

In [422]:
def t(a,*,b):
    return a+b

In [423]:
t(3,b=4)
# * 기준 오른쪽은 keyword 방식.

7

In [424]:
def s(*a):
    return a
# *a : 가변 포지션 (안넣어도 실행)

In [426]:
s()

()

In [427]:
s(1)

(1,)

In [428]:
sss = [1,2,3,4,5,]

In [429]:
s(sss)

([1, 2, 3, 4, 5],)

In [430]:
s(*sss)

(1, 2, 3, 4, 5)

In [431]:
# argument의 *는 unpacking이라고 한다.
ss ={1:3,2:3}

In [434]:
s(ss)

({1: 3, 2: 3},)

In [435]:
#parameter는 뒤에서부터 default를 채워가야한다.
def x(a=1,b):
    return a+b

SyntaxError: non-default argument follows default argument (<ipython-input-435-9cdbac8e5d34>, line 2)

In [437]:
def s(a,b=2,c=1):
    return a+b+c

In [439]:
s(a=1, 2,3) #keyword를 사용하면 계속 keyword 사용해야함.

SyntaxError: positional argument follows keyword argument (<ipython-input-439-194ad78c2246>, line 1)

In [441]:
s(a=1,b=2,c=3) #keyword 말하면 계속 keyword 사용해줘야함.

6